### ISSUE TITLE
Running on Windows with cygwin/msysgit

### ISSUE THREAD

**Issue by bkniffler** [stackdot/NodeJS-Git-Server#21]
Hi, 

I've been running this module on my dev machine (mac OS) without an issue. But when trying to run it on my windows production machine, I'm running in to problems.

Basically, I've tried this with msysgit (1.9.4) and cygwin (1.8.1.2). With cygwin, I've set the path env variable to the cygwin bin dir, so all necessary executables were available. With msysgit, I've set env paths to msysgit/bin and msysgit/libexec/git-core dirs. The results were always the same.

Also, I've tried versions 0.2.1 and 0.2.0 of this module, with the same results.

Git pull is not an issue, this works great. But as soon as i push, I'm getting this (using longjohn for extended stack trace):

**Server:**

```
LOG:  Got a PUSH call for myrepo.git
LOG:  demo is trying to push on repo: myrepo ...
LOG:  demo Successfully did a push on myrepo

D:\node\AppHost2\node_modules\longjohn\dist\long
        throw e;
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at onread (net.js:558:19)

    at fireErrorCallbacks (net.js:439:15)
    at Socket._destroy (net.js:475:3)
    at onread (net.js:558:10)
```

**Client:**

```
Pushing to http://demo:demo@xxx.com:7000/myrepo.git
POST git-receive-pack (658 bytes)
error: RPC failed; result=56, HTTP code = 0
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

I've no clue what to try now. Have you successfully run this module on a windows environment? Do you have any idea?

**Comment by Pat-Relentless** [comment]
Also having the same issue on Windows... Same error except I am getting an HTTP code of 401. I've been able to debug and the error coming from 'onread' is an EOF exception, it's trying to read past the bytes available in the stream. Why and how to fix I don't know...
