### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by pbajno** [stackdot/NodeJS-Git-Server#43]
I used the example but something is wrong.
Can't figure what...

```
/home/git-server# node index

/home/git-server/node_modules/git-server/host.js:265
          if (results.length > 0) {
                     ^
TypeError: Cannot read property 'length' of null
    at /home/git-server/node_modules/git-server/host.js:265:22
    at /home/git-server/node_modules/git-server/node_modules/async/dist/async.js                                                :3327:9
    at /home/git-server/node_modules/git-server/node_modules/async/dist/async.js                                                :421:16
    at iteratorCallback (/home/git-server/node_modules/git-server/node_modules/a                                                sync/dist/async.js:998:13)
    at /home/git-server/node_modules/git-server/node_modules/async/dist/async.js                                                :906:16
    at /home/git-server/node_modules/git-server/node_modules/async/dist/async.js                                                :3319:13
    at /home/git-server/node_modules/git-server/node_modules/async/dist/async.js                                                :4256:13
    at Object.cb [as oncomplete] (fs.js:169:19)
```

This happens with node v0.1 to v6. v8 gives me this bug: https://github.com/stackdot/NodeJS-Git-Server/issues/41

Any ideas?

**Comment by raaymax** [comment]
There is old version of this package on npm.
Workaround:
`npm install https://github.com/stackdot/NodeJS-Git-Server`
