### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by netlander** [stackdot/NodeJS-Git-Server#46]
Any ideas why I'm getting this error when trying to start the server (`npm start`) with the following snippet of code?
```
var GitServer = require('git-server');
var newUser = {
	username:'demo',
	password:'demo'
}
var newRepo = {
	name:'myrepo',
	anonRead:false,
	users: [
		{ user:newUser, permissions:['R','W'] }
	]
}
_g = new GitServer([ newRepo ]);
```

**The error**
```
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (G:\src\web\portal-development\git-wiki\git-wiki-server\git-wiki-server\node_modules\socket.io\lib\store.js:35:42)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\src\web\portal-development\git-wiki\git-wiki-server\git-wiki-server\node_modules\socket.io\lib\manager.js:14:13)
    at Module._compile (module.js:660:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! git-wiki-server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-wiki-server@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yaseen\AppData\Roaming\npm-cache\_logs\2018-03-06T18_18_44_411Z-debug.log
```

**Comment by dseif0x** [comment]
I've got the same problem.
Is there no current solution for this?

**Comment by hasezoey** [comment]
with what do you had it started? `npm start`?

**Comment by hasezoey** [comment]
it seems that you are passing directly the array,
but it sould be this:
`_g = new GitServer({repos: [ newRepo ]});`
(when it does not fucntion with `npm start` try it with `node ./yourfile.js`)

and this repo seems to be not to be updated, i would recommend [this](https://github.com/gabrielcsapo/node-git-server)

**Comment by TobiasNickel** [comment]
the solution is here: https://github.com/stackdot/NodeJS-Git-Server/issues/41
